package corm

const (
	INSERT     = "INSERT INTO"
	SELECT     = "SELECT"
	UPDATE     = "UPDATE"
	DELETE     = "DELETE"
	FROM       = "FROM"
	WHERE      = "WHERE"
	INNER_JOIN = "INNER JOIN"
	LEFT_JOIN  = "LEFT JOIN"
	RIGHT_JOIN = "RIGHT JOIN"
	AND        = "AND"
	ON         = "ON"
	IN         = "IN"
	NOT_IN     = "NOT IN"
	LIKE       = "LIKE"
	NOT_LIKE   = "NOT LIKE"
	ORDER_BY   = "ORDER BY"
	GROUP_BY   = "GROUP BY"
	LIMIT      = "LIMIT"
	OFFSET     = "OFFSET"
	HAVING     = "HAVING"
	BETWEEN    = "BETWEEN"
	SET        = "SET"
	SPACE      = " "
	COMMA      = ","
	QUES       = "?"
)
